### ISSUE TITLE
error

### ISSUE THREAD

**Issue by umarahmad125** [diggilly/kinflux_bot_God#1]
not work

**Comment by diggilly** [comment]
Hello it's working tell me where you went wrong and I will show you how to fix it

**Comment by umarahmad125** [comment]
After deploying it's only work maximum 30 mints and then failed

**Comment by diggilly** [comment]
soryy for the inconvinience but we are can you share more information so tht we can fix the error

**Comment by umarahmad125** [comment]
![IMG_20230706_213642_754](https://github.com/diggilly/kinflux_bot_God/assets/47673584/5a53d830-3ef8-4e80-aaa9-1f44cf52675b)

**Comment by umarahmad125** [comment]
![IMG_20230706_214613_649](https://github.com/diggilly/kinflux_bot_God/assets/47673584/e05a5a9b-ea61-4e2b-9bd0-7ebb81927b6f)

**Comment by diggilly** [comment]
Hello Kinflux bot god v2  is out and stable 
https://github.com/diggilly/kinflux_bot_god_v2

**Comment by diggilly** [comment]
Thank you
